package application;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;

import javafx.scene.control.*;
import javafx.scene.control.ScrollPane.ScrollBarPolicy;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.*;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Rectangle;
import javafx.stage.Window;
import javafx.scene.Cursor;

public class Main extends Application {
	@Override
	public void start(Stage primaryStage) throws FileNotFoundException {

		
		  // creating labels 
		  Button sides = new Button("Sides");
		  sides.setFont(Font.font ("Arial", 15));
		  sides.setStyle("-fx-base: #c1dbb3; ");
		  sides.setPrefHeight(25);
		  sides.setDefaultButton(false); 
		  sides.setPrefWidth(115);
		  Button entrees = new Button("Entrees");
		  entrees.setFont(Font.font ("Arial", 15));
		  entrees.setStyle("-fx-base: #c1dbb3; ");
		  entrees.setPrefHeight(25);
		  entrees.setDefaultButton(false); 
		  entrees.setPrefWidth(115);
		  Button beverages = new Button("Beverages");
		  beverages.setFont(Font.font ("Arial", 15));
		  beverages.setStyle("-fx-base: #c1dbb3; ");
		  beverages.setPrefHeight(25);
		  beverages.setDefaultButton(false); 
		  beverages.setPrefWidth(115);
		  Button name = new Button("Restaurant Name");
		  name.setFont(Font.font ("Arial", 15));
		  name.setStyle("-fx-base: #c1dbb3; ");
		  name.setPrefHeight(25);
		  name.setDefaultButton(false); 
		  name.setPrefWidth(150);
		  
		  
		  // search text field 
		  TextField search = new TextField("search");
		  search.setPrefHeight(30); 
		  search.setPrefWidth(100);
		  
		 
		  // outline food description
		  Rectangle rect1 = new Rectangle();
		  rect1.setFill(Color.TRANSPARENT);
		  rect1.setStroke(Color.BLACK);
		  rect1.setWidth(450);
		  rect1.setHeight(85);
		  Rectangle rect2 = new Rectangle();
		  rect2.setFill(Color.TRANSPARENT);
		  rect2.setStroke(Color.BLACK);
		  rect2.setWidth(450);
		  rect2.setHeight(85);
		  Rectangle rect3 = new Rectangle();
		  rect3.setFill(Color.TRANSPARENT);
		  rect3.setStroke(Color.BLACK);
		  rect3.setWidth(450);
		  rect3.setHeight(85);
		  Rectangle rect4 = new Rectangle();
		  rect4.setFill(Color.TRANSPARENT);
		  rect4.setStroke(Color.BLACK);
		  rect4.setWidth(450);
		  rect4.setHeight(85);
		  Rectangle rect5 = new Rectangle();
		  rect5.setFill(Color.TRANSPARENT);
		  rect5.setStroke(Color.BLACK);
		  rect5.setWidth(450);
		  rect5.setHeight(85);
		  Rectangle rect6 = new Rectangle();
		  rect6.setFill(Color.TRANSPARENT);
		  rect6.setStroke(Color.BLACK);
		  rect6.setWidth(450);
		  rect6.setHeight(85);
		  Rectangle rect7 = new Rectangle();
		  rect7.setFill(Color.TRANSPARENT);
		  rect7.setStroke(Color.BLACK);
		  rect7.setWidth(450);
		  rect7.setHeight(85);
		  Rectangle rect8 = new Rectangle();
		  rect8.setFill(Color.TRANSPARENT);
		  rect8.setStroke(Color.BLACK);
		  rect8.setWidth(450);
		  rect8.setHeight(85);
		  Rectangle rect9 = new Rectangle();
		  rect9.setFill(Color.TRANSPARENT);
		  rect9.setStroke(Color.BLACK);
		  rect9.setWidth(450);
		  rect9.setHeight(85);
		  Rectangle rect10 = new Rectangle();
		  rect10.setFill(Color.TRANSPARENT);
		  rect10.setStroke(Color.BLACK);
		  rect10.setWidth(450);
		  rect10.setHeight(85);
		  Rectangle rect11 = new Rectangle();
		  rect11.setFill(Color.TRANSPARENT);
		  rect11.setStroke(Color.BLACK);
		  rect11.setWidth(450);
		  rect11.setHeight(85);
		  Rectangle rect12 = new Rectangle();
		  rect12.setFill(Color.TRANSPARENT);
		  rect12.setStroke(Color.BLACK);
		  rect12.setWidth(450);
		  rect12.setHeight(85);
		  
		  
		  // food items 
		  Label friestext = new Label("Fries"); 
		  friestext.setStyle("-fx-font: 15 arial; ");
		  friestext.setTranslateX(-80);
		  friestext.setTranslateY(-20);
		  Label mactext = new Label("Mac N Cheese"); 
		  mactext.setStyle("-fx-font: 15 arial; ");
		  mactext.setTranslateX(-80);
		  mactext.setTranslateY(-20);
		  Label curdstext = new Label("Cheese Curds"); 
		  curdstext.setStyle("-fx-font: 15 arial; ");
		  curdstext.setTranslateX(-80);
		  curdstext.setTranslateY(-20);
		  Label cheesebtext = new Label("Cheese"); 
		  cheesebtext.setStyle("-fx-font: 15 arial; ");
		  cheesebtext.setTranslateX(-80);
		  cheesebtext.setTranslateY(-20);
		  cheesebtext.setPrefWidth(250);
		  Label bacontext = new Label("Bacon"); 
		  bacontext.setStyle("-fx-font: 15 arial; ");
		  bacontext.setTranslateX(-80);
		  bacontext.setTranslateY(-20);
		  Label chickentext = new Label("Chicken"); 
		  chickentext.setStyle("-fx-font: 15 arial; ");
		  chickentext.setTranslateX(-80);
		  chickentext.setTranslateY(-20);
		  Label impossibletext = new Label("Impossible"); 
		  impossibletext.setStyle("-fx-font: 15 arial; ");
		  impossibletext.setTranslateX(-80);
		  impossibletext.setTranslateY(-20);
		  Label doubletext = new Label("Double"); 
		  doubletext.setStyle("-fx-font: 15 arial; ");
		  doubletext.setTranslateX(-80);
		  doubletext.setTranslateY(-20);
		  Label stripstext = new Label("Chicken Strips"); 
		  stripstext.setStyle("-fx-font: 15 arial; ");
		  stripstext.setTranslateX(-80);
		  stripstext.setTranslateY(-20);
		  Label sodatext = new Label("Soda"); 
		  sodatext.setStyle("-fx-font: 15 arial; ");
		  sodatext.setTranslateX(-80);
		  sodatext.setTranslateY(-20);
		  Label watertext = new Label("Water"); 
		  watertext.setStyle("-fx-font: 15 arial; ");
		  watertext.setTranslateX(-80);
		  watertext.setTranslateY(-20);
		  Label lemonadetext = new Label("Lemonade"); 
		  lemonadetext.setStyle("-fx-font: 15 arial; ");
		  lemonadetext.setTranslateX(-80);
		  lemonadetext.setTranslateY(-20);
		  
		  
		  //food prices
		  Label friesprice = new Label("$3.99");
		  friesprice.setStyle("-fx-font: 15 arial; ");
		  friesprice.setTranslateX(-80);
		  friesprice.setTranslateY(10);
		  Label macprice = new Label("$2.99");
		  macprice.setStyle("-fx-font: 15 arial; ");
		  macprice.setTranslateX(-80);
		  macprice.setTranslateY(10);
		  Label curdsprice = new Label("$3.50");
		  curdsprice.setStyle("-fx-font: 15 arial; ");
		  curdsprice.setTranslateX(-80);
		  curdsprice.setTranslateY(10);
		  Label cheeseprice = new Label("$8.09");
		  cheeseprice.setStyle("-fx-font: 15 arial; ");
		  cheeseprice.setTranslateX(-80);
		  cheeseprice.setTranslateY(10);
		  Label baconprice = new Label("$8.50");
		  baconprice.setStyle("-fx-font: 15 arial; ");
		  baconprice.setTranslateX(-80);
		  baconprice.setTranslateY(10);
		  Label chickenprice = new Label("$7.99");
		  chickenprice.setStyle("-fx-font: 15 arial; ");
		  chickenprice.setTranslateX(-80);
		  chickenprice.setTranslateY(10);
		  Label impossibleprice = new Label("$7.50");
		  impossibleprice.setStyle("-fx-font: 15 arial; ");
		  impossibleprice.setTranslateX(-80);
		  impossibleprice.setTranslateY(10);
		  Label doubleprice = new Label("$8.99");
		  doubleprice.setStyle("-fx-font: 15 arial; ");
		  doubleprice.setTranslateX(-80);
		  doubleprice.setTranslateY(10);
		  Label stripsprice = new Label("$7.40");
		  stripsprice.setStyle("-fx-font: 15 arial; ");
		  stripsprice.setTranslateX(-80);
		  stripsprice.setTranslateY(10);
		  Label sodaprice = new Label("$2.99");
		  sodaprice.setStyle("-fx-font: 15 arial; ");
		  sodaprice.setTranslateX(-80);
		  sodaprice.setTranslateY(10);
		  Label waterprice = new Label("$1.00");
		  waterprice.setStyle("-fx-font: 15 arial; ");
		  waterprice.setTranslateX(-80);
		  waterprice.setTranslateY(10);
		  Label lemonadeprice = new Label("$2.99");
		  lemonadeprice.setStyle("-fx-font: 15 arial; ");
		  lemonadeprice.setTranslateX(-80);
		  lemonadeprice.setTranslateY(10);
		  
		  //food ingredients
		  Label friesingredients = new Label("Ingredients:Potatoes, Salt,");
		  friesingredients.setStyle("-fx-font: 13 arial; ");
		  friesingredients.setTranslateX(40);
		  friesingredients.setTranslateY(-10);
		  Label friesingredients1 = new Label("Vegetable Oil");
		  friesingredients1.setStyle("-fx-font: 13 arial; ");
		  friesingredients1.setTranslateX(70);
		  friesingredients1.setTranslateY(10);
		  Label macingredients = new Label("Ingredients: Pasta, Butter, Flour,");
		  macingredients.setStyle("-fx-font: 13 arial; ");
		  macingredients.setTranslateX(40);
		  macingredients.setTranslateY(-20);
		  Label macingredients1 = new Label("Milk, Sharp Cheddar, Salt, Black");
		  macingredients1.setStyle("-fx-font: 13 arial; ");
		  macingredients1.setTranslateX(40);
		  macingredients1.setTranslateY(0);
		  Label macingredients2 = new Label("Pepper, Paprika");
		  macingredients2.setStyle("-fx-font: 13 arial; ");
		  macingredients2.setTranslateX(80);
		  macingredients2.setTranslateY(20);
		  Label curdsingredients = new Label("   Ingredients: Cheese Curds,");
		  curdsingredients.setStyle("-fx-font: 13 arial; ");
		  curdsingredients.setTranslateX(40);
		  curdsingredients.setTranslateY(-20);
		  Label curdsingredients1 = new Label("Buttermilk, Baking Soda, Flour,");
		  curdsingredients1.setStyle("-fx-font: 13 arial; ");
		  curdsingredients1.setTranslateX(40);
		  curdsingredients1.setTranslateY(0);
		  Label curdsingredients2 = new Label("Garlic Salt, Eggs, Vegetable Oil");
		  curdsingredients2.setStyle("-fx-font: 13 arial; ");
		  curdsingredients2.setTranslateX(37);
		  curdsingredients2.setTranslateY(20);
		  Label cheeseingredients = new Label("Ingredients: Beef patty topped");
		  cheeseingredients.setStyle("-fx-font: 13 arial; ");
		  cheeseingredients.setTranslateX(40);
		  cheeseingredients.setTranslateY(-30);
		  Label cheeseingredients1 = new Label(" with cheddar cheese, lettuce,");
		  cheeseingredients1.setStyle("-fx-font: 13 arial; ");
		  cheeseingredients1.setTranslateX(40);
		  cheeseingredients1.setTranslateY(-10);
		  Label cheeseingredients2 = new Label("tomato, onion, mayonnaise, and");
		  cheeseingredients2.setStyle("-fx-font: 13 arial; ");
		  cheeseingredients2.setTranslateX(40);
		  cheeseingredients2.setTranslateY(10);
		  Label cheeseingredients3 = new Label("             a sesame bun");
		  cheeseingredients3.setStyle("-fx-font: 13 arial; ");
		  cheeseingredients3.setTranslateX(40);
		  cheeseingredients3.setTranslateY(30);
		  Label baconingredients = new Label("Ingredients: Beef patty topped");
		  baconingredients.setStyle("-fx-font: 13 arial; ");
		  baconingredients.setTranslateX(40);
		  baconingredients.setTranslateY(-30);
		  Label baconingredients1 = new Label(" with cheddar cheese, lettuce,");
		  baconingredients1.setStyle("-fx-font: 13 arial; ");
		  baconingredients1.setTranslateX(40);
		  baconingredients1.setTranslateY(-10);
		  Label baconingredients2 = new Label("       tomato, onion, bacon,");
		  baconingredients2.setStyle("-fx-font: 13 arial; ");
		  baconingredients2.setTranslateX(40);
		  baconingredients2.setTranslateY(10);
		  Label baconingredients3 = new Label("mayonnaise, and a sesame bun");
		  baconingredients3.setStyle("-fx-font: 13 arial; ");
		  baconingredients3.setTranslateX(40);
		  baconingredients3.setTranslateY(30);
		  Label chickeningredients = new Label("   Ingredients: Crispy chicken");
		  chickeningredients.setStyle("-fx-font: 13 arial; ");
		  chickeningredients.setTranslateX(40);
		  chickeningredients.setTranslateY(-30);
		  Label chickeningredients1 = new Label("  topped with cheddar cheese,");
		  chickeningredients1.setStyle("-fx-font: 13 arial; ");
		  chickeningredients1.setTranslateX(40);
		  chickeningredients1.setTranslateY(-10);
		  Label chickeningredients2 = new Label("        lettuce, tomato, onion,");
		  chickeningredients2.setStyle("-fx-font: 13 arial; ");
		  chickeningredients2.setTranslateX(40);
		  chickeningredients2.setTranslateY(10);
		  Label chickeningredients3 = new Label("mayonnaise, and a sesame bun");
		  chickeningredients3.setStyle("-fx-font: 13 arial; ");
		  chickeningredients3.setTranslateX(40);
		  chickeningredients3.setTranslateY(30);
		  Label impossibleingredients = new Label(" Ingredients: Impossible burger");
		  impossibleingredients.setStyle("-fx-font: 13 arial; ");
		  impossibleingredients.setTranslateX(40);
		  impossibleingredients.setTranslateY(-30);
		  Label impossibleingredients1 = new Label("   topped with cheddar cheese,");
		  impossibleingredients1.setStyle("-fx-font: 13 arial; ");
		  impossibleingredients1.setTranslateX(40);
		  impossibleingredients1.setTranslateY(-10);
		  Label impossibleingredients2 = new Label("        lettuce, tomato, onion,");
		  impossibleingredients2.setStyle("-fx-font: 13 arial; ");
		  impossibleingredients2.setTranslateX(40);
		  impossibleingredients2.setTranslateY(10);
		  Label impossibleingredients3 = new Label("mayonnaise, and a sesame bun");
		  impossibleingredients3.setStyle("-fx-font: 13 arial; ");
		  impossibleingredients3.setTranslateX(40);
		  impossibleingredients3.setTranslateY(30);
		  Label doubleingredients = new Label("   Ingredients: Double burger");
		  doubleingredients.setStyle("-fx-font: 13 arial; ");
		  doubleingredients.setTranslateX(40);
		  doubleingredients.setTranslateY(-30);
		  Label doubleingredients1 = new Label("  topped with cheddar cheese,");
		  doubleingredients1.setStyle("-fx-font: 13 arial; ");
		  doubleingredients1.setTranslateX(40);
		  doubleingredients1.setTranslateY(-10);
		  Label doubleingredients2 = new Label("      lettuce, tomato, onions,");
		  doubleingredients2.setStyle("-fx-font: 13 arial; ");
		  doubleingredients2.setTranslateX(40);
		  doubleingredients2.setTranslateY(10);
		  Label doubleingredients3 = new Label("mayonnaise and a sesame bun");
		  doubleingredients3.setStyle("-fx-font: 13 arial; ");
		  doubleingredients3.setTranslateX(40);
		  doubleingredients3.setTranslateY(30);
		  Label stripsingredients = new Label("   Ingredients: Breaded chicken");
		  stripsingredients.setStyle("-fx-font: 13 arial; ");
		  stripsingredients.setTranslateX(40);
		  stripsingredients.setTranslateY(-30);
		  Label stripsingredients1 = new Label(" breast seasoned with garlic salt,");
		  stripsingredients1.setStyle("-fx-font: 13 arial; ");
		  stripsingredients1.setTranslateX(40);
		  stripsingredients1.setTranslateY(-10);
		  Label stripsingredients2 = new Label(" dried basil, paprika, and pepper.");
		  stripsingredients2.setStyle("-fx-font: 13 arial; ");
		  stripsingredients2.setTranslateX(40);
		  stripsingredients2.setTranslateY(10);
		  Label stripsingredients3 = new Label("Served with Ketchup and Mustard");
		  stripsingredients3.setStyle("-fx-font: 13 arial; ");
		  stripsingredients3.setTranslateX(40);
		  stripsingredients3.setTranslateY(30);
		  Label sodaoptions = new Label(" Available options: Sprite, Coke,");
		  sodaoptions.setStyle("-fx-font: 13 arial; ");
		  sodaoptions.setTranslateX(40);
		  sodaoptions.setTranslateY(-20);
		  Label sodaoptions1 = new Label("Pepsi, Dr. Pepper, Mountain Dew,");
		  sodaoptions1.setStyle("-fx-font: 13 arial; ");
		  sodaoptions1.setTranslateX(40);
		  sodaoptions1.setTranslateY(0);
		  Label sodaoptions2 = new Label("Canada Dry (Decide upon pickup)");
		  sodaoptions2.setStyle("-fx-font: 13 arial; ");
		  sodaoptions2.setTranslateX(40);
		  sodaoptions2.setTranslateY(20);
		  Label wateringredients = new Label("   Ingredients: Purified Water,");
		  wateringredients.setStyle("-fx-font: 13 arial; ");
		  wateringredients.setTranslateX(40);
		  wateringredients.setTranslateY(-20);
		  Label wateringredients1 = new Label("Magnesium Sulfate, Potassium");
		  wateringredients1.setStyle("-fx-font: 13 arial; ");
		  wateringredients1.setTranslateX(40);
		  wateringredients1.setTranslateY(0);
		  Label wateringredients2 = new Label("            Chloride, Salt");
		  wateringredients2.setStyle("-fx-font: 13 arial; ");
		  wateringredients2.setTranslateX(40);
		  wateringredients2.setTranslateY(20);
		  Label lemonadeingredients = new Label("    Ingredients: Water, High");
		  lemonadeingredients.setStyle("-fx-font: 13 arial; ");
		  lemonadeingredients.setTranslateX(40);
		  lemonadeingredients.setTranslateY(-30);
		  Label lemonadeingredients1 = new Label("   Fructose Corn Syrup, Citric");
		  lemonadeingredients1.setStyle("-fx-font: 13 arial; ");
		  lemonadeingredients1.setTranslateX(40);
		  lemonadeingredients1.setTranslateY(-10);
		  Label lemonadeingredients2 = new Label("Acid, Sodium Benzoate, Lemon");
		  lemonadeingredients2.setStyle("-fx-font: 13 arial; ");
		  lemonadeingredients2.setTranslateX(40);
		  lemonadeingredients2.setTranslateY(10);
		  Label lemonadeingredients3 = new Label("                   Juice");
		  lemonadeingredients3.setStyle("-fx-font: 13 arial; ");
		  lemonadeingredients3.setTranslateX(40);
		  lemonadeingredients3.setTranslateY(30);
		  
		  
		  // images 
		  ImageView fries = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/fries.jpg")));
		  fries.setFitHeight(85);
		  fries.setFitWidth(115);
		  ImageView macncheese = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/macncheese.jpg")));
		  macncheese.setFitHeight(85);
		  macncheese.setPreserveRatio(true);
		  ImageView cheesecurds = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/cheesecurds.jpg")));
		  cheesecurds.setFitHeight(85);
		  cheesecurds.setFitWidth(115);
		  ImageView cheeseburger = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/cheeseburger.jpg")));
		  cheeseburger.setFitHeight(85);
		  cheeseburger.setPreserveRatio(true);
		  ImageView bacon = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/bacon.jpeg")));
		  bacon.setFitHeight(85);
		  bacon.setPreserveRatio(true);
		  ImageView chickensando = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/chickensando.jpg")));
		  chickensando.setFitHeight(85);
		  chickensando.setFitWidth(115);
		  ImageView impossible = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/impossible.jpeg")));
		  impossible.setFitHeight(85);
		  impossible.setFitWidth(115);
		  ImageView doublecheese = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/doublecheese.jpg")));
		  doublecheese.setFitHeight(85);
		  doublecheese.setFitWidth(115);
		  ImageView tenders = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/tenders.jpg")));
		  tenders.setFitHeight(85);
		  tenders.setPreserveRatio(true);
		  ImageView soda = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/soda.jpeg")));
		  soda.setFitHeight(85);
		  soda.setFitWidth(115);
		  ImageView water = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/water.jpg")));
		  water.setFitHeight(85);
		  water.setFitWidth(115);
		  ImageView lemonade = new ImageView(new Image(new FileInputStream("C:/Users/cluec/Pictures/lemonade.jpg")));
		  lemonade.setFitHeight(85);
		  lemonade.setFitWidth(115);
		  
	
		  // buttons 
		  Button loginButton = new Button("Login");
		  loginButton.setStyle("-fx-font: 18 arial; ");
		  loginButton.setStyle("-fx-base: #fec89a; "); 
		  loginButton.setPrefHeight(30);
		  loginButton.setDefaultButton(true); 
		  loginButton.setPrefWidth(60);
		  Button cartButton = new Button("Cart");
		  cartButton.setStyle("-fx-font: 18 arial; ");
		  cartButton.setStyle("-fx-base: #fec89a; "); 
		  cartButton.setPrefHeight(30);
		  cartButton.setDefaultButton(true); 
		  cartButton.setPrefWidth(60);
		  Button addButton1 = new Button("add to cart");
		  addButton1.setFont(Font.font ("Arial", 12));
		  addButton1.setStyle("-fx-base: #e5989b; ");
		  addButton1.setPrefHeight(30);
		  addButton1.setDefaultButton(true); 
		  addButton1.setPrefWidth(80);
		  Button addButton2 = new Button("add to cart");
		  addButton2.setFont(Font.font ("Arial", 12));
		  addButton2.setStyle("-fx-base: #e5989b; ");
		  addButton2.setPrefHeight(30);
		  addButton2.setDefaultButton(true); 
		  addButton2.setPrefWidth(80);
		  Button addButton3 = new Button("add to cart");
		  addButton3.setFont(Font.font ("Arial", 12));
		  addButton3.setStyle("-fx-base: #e5989b; ");
		  addButton3.setPrefHeight(30);
		  addButton3.setDefaultButton(true); 
		  addButton3.setPrefWidth(80);
		  Button addButton4 = new Button("add to cart");
		  addButton4.setFont(Font.font ("Arial", 12));
		  addButton4.setStyle("-fx-base: #e5989b; ");
		  addButton4.setPrefHeight(30);
		  addButton4.setDefaultButton(true); 
		  addButton4.setPrefWidth(80);
		  Button addButton5 = new Button("add to cart");
		  addButton5.setFont(Font.font ("Arial", 12));
		  addButton5.setStyle("-fx-base: #e5989b; ");
		  addButton5.setPrefHeight(30);
		  addButton5.setDefaultButton(true); 
		  addButton5.setPrefWidth(80);
		  Button addButton6 = new Button("add to cart");
		  addButton6.setFont(Font.font ("Arial", 12));
		  addButton6.setStyle("-fx-base: #e5989b; ");
		  addButton6.setPrefHeight(30);
		  addButton6.setDefaultButton(true); 
		  addButton6.setPrefWidth(80);
		  Button addButton7 = new Button("add to cart");
		  addButton7.setFont(Font.font ("Arial", 12));
		  addButton7.setStyle("-fx-base: #e5989b; ");
		  addButton7.setPrefHeight(30);
		  addButton7.setDefaultButton(true); 
		  addButton7.setPrefWidth(80);
		  Button addButton8 = new Button("add to cart");
		  addButton8.setFont(Font.font ("Arial", 12));
		  addButton8.setStyle("-fx-base: #e5989b; ");
		  addButton8.setPrefHeight(30);
		  addButton8.setDefaultButton(true); 
		  addButton8.setPrefWidth(80);
		  Button addButton9 = new Button("add to cart");
		  addButton9.setFont(Font.font ("Arial", 12));
		  addButton9.setStyle("-fx-base: #e5989b; ");
		  addButton9.setPrefHeight(30);
		  addButton9.setDefaultButton(true); 
		  addButton9.setPrefWidth(80);
		  Button addButton10 = new Button("add to cart");
		  addButton10.setFont(Font.font ("Arial", 12));
		  addButton10.setStyle("-fx-base: #e5989b; ");
		  addButton10.setPrefHeight(30);
		  addButton10.setDefaultButton(true); 
		  addButton10.setPrefWidth(80);
		  Button addButton11 = new Button("add to cart");
		  addButton11.setFont(Font.font ("Arial", 12));
		  addButton11.setStyle("-fx-base: #e5989b; ");
		  addButton11.setPrefHeight(30);
		  addButton11.setDefaultButton(true); 
		  addButton11.setPrefWidth(80);
		  Button addButton12 = new Button("add to cart");
		  addButton12.setFont(Font.font ("Arial", 12));
		  addButton12.setStyle("-fx-base: #e5989b; ");
		  addButton12.setPrefHeight(30);
		  addButton12.setDefaultButton(true); 
		  addButton12.setPrefWidth(80);
		  

		  GridPane gridPane = new GridPane();
		  gridPane.setMinSize(800, 1000);
		
		
		  //columns and rows
		  gridPane.getColumnConstraints().add(new ColumnConstraints(80));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(130));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(100));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(200));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(50));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(90));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(30));
		  gridPane.getColumnConstraints().add(new ColumnConstraints(60));
		  gridPane.getRowConstraints().add(new RowConstraints(50));
		  gridPane.getRowConstraints().add(new RowConstraints(50));
		  gridPane.getRowConstraints().add(new RowConstraints(70));
		  gridPane.getRowConstraints().add(new RowConstraints(120));
		  gridPane.getRowConstraints().add(new RowConstraints(70));
		  gridPane.getRowConstraints().add(new RowConstraints(50));
		  gridPane.getRowConstraints().add(new RowConstraints(70));
		  gridPane.getRowConstraints().add(new RowConstraints(120));
		  gridPane.getRowConstraints().add(new RowConstraints(70));
		  gridPane.getRowConstraints().add(new RowConstraints(120));
		  gridPane.getRowConstraints().add(new RowConstraints(70));
		  gridPane.getRowConstraints().add(new RowConstraints(120));
		  gridPane.getRowConstraints().add(new RowConstraints(10));
		  gridPane.getRowConstraints().add(new RowConstraints(100));
		  gridPane.getRowConstraints().add(new RowConstraints(90));
		  gridPane.getRowConstraints().add(new RowConstraints(100));
		
		  // alignment 
		  gridPane.add(loginButton, 0, 0);
		  gridPane.add(cartButton, 7, 0);
		  gridPane.add(addButton1, 5, 2);
		  gridPane.add(addButton2, 5, 3);
		  gridPane.add(addButton3, 5, 4);
		  gridPane.add(addButton4, 5, 6);
		  gridPane.add(addButton5, 5, 7);
		  gridPane.add(addButton6, 5, 8);
		  gridPane.add(addButton7, 5, 9);
		  gridPane.add(addButton8, 5, 10);
		  gridPane.add(addButton9, 5, 11);
		  gridPane.add(addButton10, 5, 13);
		  gridPane.add(addButton11, 5, 14);
		  gridPane.add(addButton12, 5, 15);
		  gridPane.add(search, 5, 0);
		   
		  gridPane.add(name, 3, 0);
		  gridPane.add(sides, 1, 1);
		  gridPane.add(fries, 1, 2);
		  gridPane.add(macncheese, 1, 3);
		  gridPane.add(cheesecurds, 1, 4);
		  gridPane.add(entrees, 1, 5);
		  gridPane.add(cheeseburger, 1, 6);
		  gridPane.add(bacon, 1, 7);
		  gridPane.add(chickensando, 1, 8);
		  gridPane.add(impossible, 1, 9);
		  gridPane.add(doublecheese, 1, 10);
		  gridPane.add(tenders, 1, 11);
		  gridPane.add(beverages, 1, 12);
		  gridPane.add(soda, 1, 13);
		  gridPane.add(water, 1, 14);
		  gridPane.add(lemonade, 1, 15);
		 
		  gridPane.add(rect1, 2, 2);
		  gridPane.add(rect2, 2, 3);
		  gridPane.add(rect3, 2, 4);
		  gridPane.add(rect4, 2, 6);
		  gridPane.add(rect5, 2, 7);
		  gridPane.add(rect6, 2, 8);
		  gridPane.add(rect7, 2, 9);
		  gridPane.add(rect8, 2, 10);
		  gridPane.add(rect9, 2, 11);
		  gridPane.add(rect10, 2, 13);
		  gridPane.add(rect11, 2, 14);
		  gridPane.add(rect12, 2, 15);
		 
		  gridPane.add(friestext, 3, 2);
		  gridPane.add(mactext, 3, 3);
		  gridPane.add(curdstext, 3, 4);
		  gridPane.add(cheesebtext, 3, 6);
		  gridPane.add(bacontext, 3, 7);
		  gridPane.add(chickentext, 3, 8);
		  gridPane.add(impossibletext, 3, 9);
		  gridPane.add(doubletext, 3, 10);
		  gridPane.add(stripstext, 3, 11);
		  gridPane.add(sodatext, 3, 13);
		  gridPane.add(watertext, 3, 14);
		  gridPane.add(lemonadetext, 3, 15);
		 
		  gridPane.add(friesprice, 3, 2);
		  gridPane.add(macprice, 3, 3);
		  gridPane.add(curdsprice, 3, 4);
		  gridPane.add(cheeseprice, 3, 6);
		  gridPane.add(baconprice, 3, 7);
		  gridPane.add(chickenprice, 3, 8);
		  gridPane.add(impossibleprice, 3, 9);
		  gridPane.add(doubleprice, 3, 10);
		  gridPane.add(stripsprice, 3, 11);
		  gridPane.add(sodaprice, 3, 13);
		  gridPane.add(waterprice, 3, 14);
		  gridPane.add(lemonadeprice, 3, 15);
		  
		  gridPane.add(friesingredients, 3, 2);
		  gridPane.add(friesingredients1, 3, 2);
		  gridPane.add(macingredients, 3, 3);
		  gridPane.add(macingredients1, 3, 3);
		  gridPane.add(macingredients2, 3, 3);
		  gridPane.add(curdsingredients, 3, 4);
		  gridPane.add(curdsingredients1, 3, 4);
		  gridPane.add(curdsingredients2, 3, 4);
		  gridPane.add(cheeseingredients, 3, 6);
		  gridPane.add(cheeseingredients1, 3, 6);
		  gridPane.add(cheeseingredients2, 3, 6);
		  gridPane.add(cheeseingredients3, 3, 6);
		  gridPane.add(baconingredients, 3, 7);
		  gridPane.add(baconingredients1, 3, 7);
		  gridPane.add(baconingredients2, 3, 7);
		  gridPane.add(baconingredients3, 3, 7);
		  gridPane.add(chickeningredients, 3, 8);
		  gridPane.add(chickeningredients1, 3, 8);
		  gridPane.add(chickeningredients2, 3, 8);
		  gridPane.add(chickeningredients3, 3, 8);
		  gridPane.add(impossibleingredients, 3, 9);
		  gridPane.add(impossibleingredients1, 3, 9);
		  gridPane.add(impossibleingredients2, 3, 9);
		  gridPane.add(impossibleingredients3, 3, 9);
		  gridPane.add(doubleingredients, 3, 10);
		  gridPane.add(doubleingredients1, 3, 10);
		  gridPane.add(doubleingredients2, 3, 10);
		  gridPane.add(doubleingredients3, 3, 10);
		  gridPane.add(stripsingredients, 3, 11);
		  gridPane.add(stripsingredients1, 3, 11);
		  gridPane.add(stripsingredients2, 3, 11);
		  gridPane.add(stripsingredients3, 3, 11);
		  gridPane.add(sodaoptions, 3, 13);
		  gridPane.add(sodaoptions1, 3, 13);
		  gridPane.add(sodaoptions2, 3, 13);
		  gridPane.add(wateringredients, 3, 14);
		  gridPane.add(wateringredients1, 3, 14);
		  gridPane.add(wateringredients2, 3, 14);
		  gridPane.add(lemonadeingredients, 3, 15);
		  gridPane.add(lemonadeingredients1, 3, 15);
		  gridPane.add(lemonadeingredients2, 3, 15);
		  gridPane.add(lemonadeingredients3, 3, 15);
		 
		 
		  ScrollPane scroll = new ScrollPane();
		  scroll.setPrefSize(755, 800);
		  scroll.setContent(gridPane);

		  Scene scene = new Scene(scroll);

		  primaryStage.setTitle("Restaurant Name");
		  primaryStage.setScene(scene);
		  primaryStage.show();
	}

	public static void main(String[] args) {
		  launch(args);
	}
}
